### ISSUE TITLE
Warning message in dexter.to.unimirt()

### ISSUE THREAD

**Issue by mjcarroll1985** [CambridgeAssessmentResearch/unimirt#1]
A warning message is produced in dexter.to.unimirt when the function checks the class of the data supplied.

The following line:
if (class(dexter.dat) == "SQLiteConnection") {

Could be replaced with:
if (any(class(dexter.dat) == "SQLiteConnection")) {
or
if (all(class(dexter.dat) == "SQLiteConnection")) {

to prevent the issue

**Comment by TomBentonCA** [comment]
Function updated. Issue resolved.
